// Real companies database with comprehensive stock data
export interface RealCompany {
  id: string;
  symbol: string;
  name: string;
  price: number;
  change: number;
  changePercent: number;
  marketCap: string;
  volume: number;
  country: string;
  sector: string;
  pe: number;
  dividend: number;
  beta: number;
  eps: number;
  week52High: number;
  week52Low: number;
  avgVolume: number;
  description: string;
  ceo: string;
  founded: string;
  employees: string;
  revenue: string;
  industry: string;
  exchange: string;
  isWatched: boolean;
}

export const TOP_50_COMPANIES: RealCompany[] = [
  // Top 10 Tech Giants
  {
    id: "aapl",
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 175.43,
    change: 2.14,
    changePercent: 1.23,
    marketCap: "2.7T",
    volume: 64582347,
    country: "United States",
    sector: "technology",
    pe: 28.5,
    dividend: 0.56,
    beta: 1.2,
    eps: 6.16,
    week52High: 199.62,
    week52Low: 164.08,
    avgVolume: 56789012,
    description:
      "Apple designs, manufactures, and markets smartphones, personal computers, tablets, wearables, and accessories.",
    ceo: "Tim Cook",
    founded: "1976",
    employees: "164,000",
    revenue: "394.3B",
    industry: "Consumer Electronics",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "msft",
    symbol: "MSFT",
    name: "Microsoft Corporation",
    price: 378.85,
    change: 4.52,
    changePercent: 1.21,
    marketCap: "2.8T",
    volume: 32847392,
    country: "United States",
    sector: "technology",
    pe: 32.1,
    dividend: 2.72,
    beta: 0.9,
    eps: 11.05,
    week52High: 384.3,
    week52Low: 309.45,
    avgVolume: 24567890,
    description:
      "Microsoft develops, licenses, and supports software, services, devices, and solutions worldwide.",
    ceo: "Satya Nadella",
    founded: "1975",
    employees: "221,000",
    revenue: "211.9B",
    industry: "Software",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "googl",
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    price: 138.21,
    change: -1.23,
    changePercent: -0.88,
    marketCap: "1.8T",
    volume: 28394756,
    country: "United States",
    sector: "technology",
    pe: 25.4,
    dividend: 0.0,
    beta: 1.1,
    eps: 5.8,
    week52High: 153.78,
    week52Low: 83.45,
    avgVolume: 29345678,
    description:
      "Alphabet provides online advertising services in the United States, Europe, the Middle East, Africa, the Asia-Pacific, Canada, and Latin America.",
    ceo: "Sundar Pichai",
    founded: "1998",
    employees: "182,000",
    revenue: "282.8B",
    industry: "Internet Services",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "amzn",
    symbol: "AMZN",
    name: "Amazon.com Inc.",
    price: 144.78,
    change: -0.65,
    changePercent: -0.45,
    marketCap: "1.5T",
    volume: 45673821,
    country: "United States",
    sector: "consumer",
    pe: 45.2,
    dividend: 0.0,
    beta: 1.3,
    eps: 3.2,
    week52High: 170.0,
    week52Low: 118.35,
    avgVolume: 41234567,
    description:
      "Amazon offers a range of products and services through its websites and applications including retail sales, advertising services, and web services.",
    ceo: "Andy Jassy",
    founded: "1994",
    employees: "1,541,000",
    revenue: "574.8B",
    industry: "E-commerce",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "nvda",
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    price: 721.33,
    change: 15.43,
    changePercent: 2.18,
    marketCap: "1.8T",
    volume: 45738294,
    country: "United States",
    sector: "technology",
    pe: 78.9,
    dividend: 0.16,
    beta: 1.7,
    eps: 9.12,
    week52High: 974.0,
    week52Low: 390.55,
    avgVolume: 51234567,
    description:
      "NVIDIA provides graphics, computing and networking solutions for data centers, automotive, gaming, and professional visualization markets.",
    ceo: "Jensen Huang",
    founded: "1993",
    employees: "29,600",
    revenue: "126.0B",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "tsla",
    symbol: "TSLA",
    name: "Tesla Inc.",
    price: 242.68,
    change: -3.45,
    changePercent: -1.4,
    marketCap: "782B",
    volume: 89573829,
    country: "United States",
    sector: "consumer",
    pe: 85.6,
    dividend: 0.0,
    beta: 2.1,
    eps: 2.84,
    week52High: 299.29,
    week52Low: 138.8,
    avgVolume: 78234567,
    description:
      "Tesla designs, develops, manufactures, leases, and sells electric vehicles, and energy generation and storage systems worldwide.",
    ceo: "Elon Musk",
    founded: "2003",
    employees: "140,473",
    revenue: "96.8B",
    industry: "Electric Vehicles",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "meta",
    symbol: "META",
    name: "Meta Platforms Inc.",
    price: 334.57,
    change: 5.67,
    changePercent: 1.72,
    marketCap: "849B",
    volume: 23456789,
    country: "United States",
    sector: "technology",
    pe: 23.8,
    dividend: 2.0,
    beta: 1.3,
    eps: 14.87,
    week52High: 384.33,
    week52Low: 274.38,
    avgVolume: 19876543,
    description:
      "Meta builds technologies that help people connect, find communities, and grow businesses across Facebook, Instagram, WhatsApp, and Threads.",
    ceo: "Mark Zuckerberg",
    founded: "2004",
    employees: "67,317",
    revenue: "134.9B",
    industry: "Social Media",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "nflx",
    symbol: "NFLX",
    name: "Netflix Inc.",
    price: 487.23,
    change: 8.94,
    changePercent: 1.87,
    marketCap: "209B",
    volume: 4567890,
    country: "United States",
    sector: "telecommunications",
    pe: 44.2,
    dividend: 0.0,
    beta: 1.1,
    eps: 11.05,
    week52High: 505.85,
    week52Low: 344.73,
    avgVolume: 4123456,
    description:
      "Netflix is a global streaming entertainment service with over 238 million paid memberships in more than 190 countries.",
    ceo: "Ted Sarandos",
    founded: "1997",
    employees: "13,000",
    revenue: "31.6B",
    industry: "Streaming Entertainment",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "orcl",
    symbol: "ORCL",
    name: "Oracle Corporation",
    price: 112.45,
    change: 1.23,
    changePercent: 1.11,
    marketCap: "312B",
    volume: 12345678,
    country: "United States",
    sector: "technology",
    pe: 35.6,
    dividend: 1.28,
    beta: 1.0,
    eps: 3.16,
    week52High: 127.54,
    week52Low: 99.26,
    avgVolume: 11234567,
    description:
      "Oracle provides products and services that address enterprise information technology environments worldwide.",
    ceo: "Safra Catz",
    founded: "1977",
    employees: "164,000",
    revenue: "49.9B",
    industry: "Enterprise Software",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "crm",
    symbol: "CRM",
    name: "Salesforce Inc.",
    price: 267.89,
    change: 3.45,
    changePercent: 1.31,
    marketCap: "259B",
    volume: 5678901,
    country: "United States",
    sector: "technology",
    pe: 58.9,
    dividend: 0.0,
    beta: 1.2,
    eps: 4.55,
    week52High: 295.53,
    week52Low: 211.76,
    avgVolume: 5234567,
    description:
      "Salesforce provides customer relationship management technology that brings companies and customers together worldwide.",
    ceo: "Marc Benioff",
    founded: "1999",
    employees: "79,390",
    revenue: "31.4B",
    industry: "Cloud Software",
    exchange: "NYSE",
    isWatched: false,
  },

  // Financial Services
  {
    id: "jpm",
    symbol: "JPM",
    name: "JPMorgan Chase & Co.",
    price: 178.34,
    change: 2.45,
    changePercent: 1.39,
    marketCap: "523B",
    volume: 8901234,
    country: "United States",
    sector: "finance",
    pe: 12.8,
    dividend: 4.0,
    beta: 1.1,
    eps: 13.93,
    week52High: 194.99,
    week52Low: 135.19,
    avgVolume: 8456789,
    description:
      "JPMorgan Chase & Co. operates as a financial services company worldwide, providing investment banking, financial services for consumers and small businesses, commercial banking, financial transaction processing, and asset management.",
    ceo: "Jamie Dimon",
    founded: "1799",
    employees: "309,926",
    revenue: "162.4B",
    industry: "Banking",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "bac",
    symbol: "BAC",
    name: "Bank of America Corp.",
    price: 38.67,
    change: 0.23,
    changePercent: 0.6,
    marketCap: "298B",
    volume: 45678901,
    country: "United States",
    sector: "finance",
    pe: 14.2,
    dividend: 3.6,
    beta: 1.3,
    eps: 2.72,
    week52High: 40.53,
    week52Low: 24.96,
    avgVolume: 42345678,
    description:
      "Bank of America Corporation provides banking and financial products and services for individual consumers, small and middle-market businesses, institutional investors, large corporations, and governments worldwide.",
    ceo: "Brian Moynihan",
    founded: "1904",
    employees: "216,823",
    revenue: "94.9B",
    industry: "Banking",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "wfc",
    symbol: "WFC",
    name: "Wells Fargo & Company",
    price: 54.23,
    change: 1.12,
    changePercent: 2.11,
    marketCap: "196B",
    volume: 23456789,
    country: "United States",
    sector: "finance",
    pe: 13.1,
    dividend: 3.2,
    beta: 1.2,
    eps: 4.14,
    week52High: 57.38,
    week52Low: 40.01,
    avgVolume: 21234567,
    description:
      "Wells Fargo & Company provides banking, investment and mortgage products and services, as well as consumer and commercial finance, through banking locations and offices, the internet, and other distribution channels.",
    ceo: "Charlie Scharf",
    founded: "1852",
    employees: "238,698",
    revenue: "73.8B",
    industry: "Banking",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "gs",
    symbol: "GS",
    name: "The Goldman Sachs Group Inc.",
    price: 389.45,
    change: 4.67,
    changePercent: 1.21,
    marketCap: "133B",
    volume: 1234567,
    country: "United States",
    sector: "finance",
    pe: 15.6,
    dividend: 2.8,
    beta: 1.4,
    eps: 24.95,
    week52High: 440.2,
    week52Low: 277.84,
    avgVolume: 1876543,
    description:
      "The Goldman Sachs Group, Inc., operates as an investment banking, securities, and investment management company worldwide.",
    ceo: "David Solomon",
    founded: "1869",
    employees: "48,500",
    revenue: "44.9B",
    industry: "Investment Banking",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "ms",
    symbol: "MS",
    name: "Morgan Stanley",
    price: 98.76,
    change: 1.87,
    changePercent: 1.93,
    marketCap: "168B",
    volume: 6789012,
    country: "United States",
    sector: "finance",
    pe: 16.2,
    dividend: 3.7,
    beta: 1.3,
    eps: 6.09,
    week52High: 109.73,
    week52Low: 72.23,
    avgVolume: 6123456,
    description:
      "Morgan Stanley provides various financial products and services to corporations, governments, financial institutions, and individuals worldwide.",
    ceo: "James Gorman",
    founded: "1935",
    employees: "81,567",
    revenue: "53.7B",
    industry: "Investment Banking",
    exchange: "NYSE",
    isWatched: false,
  },

  // Healthcare & Pharmaceuticals
  {
    id: "jnj",
    symbol: "JNJ",
    name: "Johnson & Johnson",
    price: 162.34,
    change: 0.89,
    changePercent: 0.55,
    marketCap: "425B",
    volume: 12345678,
    country: "United States",
    sector: "healthcare",
    pe: 15.8,
    dividend: 4.05,
    beta: 0.7,
    eps: 10.27,
    week52High: 175.83,
    week52Low: 143.13,
    avgVolume: 11234567,
    description:
      "Johnson & Johnson researches, develops, manufactures, and sells various products in the healthcare field worldwide.",
    ceo: "Joaquin Duato",
    founded: "1886",
    employees: "152,700",
    revenue: "85.2B",
    industry: "Pharmaceuticals",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "pfe",
    symbol: "PFE",
    name: "Pfizer Inc.",
    price: 29.45,
    change: -0.34,
    changePercent: -1.14,
    marketCap: "166B",
    volume: 23456789,
    country: "United States",
    sector: "healthcare",
    pe: 13.2,
    dividend: 6.2,
    beta: 0.8,
    eps: 2.23,
    week52High: 41.16,
    week52Low: 25.2,
    avgVolume: 28765432,
    description:
      "Pfizer Inc. discovers, develops, manufactures, markets, distributes, and sells biopharmaceutical products worldwide.",
    ceo: "Albert Bourla",
    founded: "1849",
    employees: "83,000",
    revenue: "58.5B",
    industry: "Pharmaceuticals",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "abbv",
    symbol: "ABBV",
    name: "AbbVie Inc.",
    price: 173.89,
    change: 2.34,
    changePercent: 1.37,
    marketCap: "307B",
    volume: 6789012,
    country: "United States",
    sector: "healthcare",
    pe: 15.1,
    dividend: 5.6,
    beta: 0.6,
    eps: 11.51,
    week52High: 175.91,
    week52Low: 128.93,
    avgVolume: 6234567,
    description:
      "AbbVie Inc. discovers, develops, manufactures, and sells pharmaceuticals worldwide.",
    ceo: "Richard Gonzalez",
    founded: "2013",
    employees: "50,000",
    revenue: "58.1B",
    industry: "Pharmaceuticals",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "mrk",
    symbol: "MRK",
    name: "Merck & Co. Inc.",
    price: 108.67,
    change: 1.45,
    changePercent: 1.35,
    marketCap: "275B",
    volume: 8901234,
    country: "United States",
    sector: "healthcare",
    pe: 16.8,
    dividend: 2.92,
    beta: 0.9,
    eps: 6.47,
    week52High: 129.9,
    week52Low: 94.92,
    avgVolume: 8345678,
    description:
      "Merck & Co., Inc. operates as a healthcare company worldwide, offering health solutions through its prescription medicines, vaccines, biologic therapies, and animal health products.",
    ceo: "Robert Davis",
    founded: "1891",
    employees: "68,000",
    revenue: "60.1B",
    industry: "Pharmaceuticals",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "lly",
    symbol: "LLY",
    name: "Eli Lilly and Company",
    price: 567.89,
    change: 8.23,
    changePercent: 1.47,
    marketCap: "541B",
    volume: 2345678,
    country: "United States",
    sector: "healthcare",
    pe: 68.9,
    dividend: 1.4,
    beta: 0.5,
    eps: 8.24,
    week52High: 972.53,
    week52Low: 497.61,
    avgVolume: 2876543,
    description:
      "Eli Lilly and Company discovers, develops, and markets human pharmaceuticals worldwide.",
    ceo: "David Ricks",
    founded: "1876",
    employees: "39,000",
    revenue: "34.1B",
    industry: "Pharmaceuticals",
    exchange: "NYSE",
    isWatched: false,
  },

  // Consumer Goods & Retail
  {
    id: "pg",
    symbol: "PG",
    name: "The Procter & Gamble Company",
    price: 156.78,
    change: 1.23,
    changePercent: 0.79,
    marketCap: "365B",
    volume: 5678901,
    country: "United States",
    sector: "consumer",
    pe: 26.3,
    dividend: 2.3,
    beta: 0.4,
    eps: 5.96,
    week52High: 165.35,
    week52Low: 142.94,
    avgVolume: 5234567,
    description:
      "The Procter & Gamble Company provides branded consumer packaged goods worldwide.",
    ceo: "Jon Moeller",
    founded: "1837",
    employees: "106,000",
    revenue: "82.0B",
    industry: "Consumer Goods",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "ko",
    symbol: "KO",
    name: "The Coca-Cola Company",
    price: 59.34,
    change: 0.45,
    changePercent: 0.76,
    marketCap: "257B",
    volume: 12345678,
    country: "United States",
    sector: "consumer",
    pe: 26.8,
    dividend: 3.0,
    beta: 0.6,
    eps: 2.21,
    week52High: 65.52,
    week52Low: 51.55,
    avgVolume: 11876543,
    description:
      "The Coca-Cola Company manufactures, markets, and sells various nonalcoholic beverages worldwide.",
    ceo: "James Quincey",
    founded: "1892",
    employees: "82,500",
    revenue: "45.8B",
    industry: "Beverages",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "pep",
    symbol: "PEP",
    name: "PepsiCo Inc.",
    price: 169.45,
    change: 2.12,
    changePercent: 1.27,
    marketCap: "234B",
    volume: 3456789,
    country: "United States",
    sector: "consumer",
    pe: 25.1,
    dividend: 2.9,
    beta: 0.7,
    eps: 6.76,
    week52High: 177.62,
    week52Low: 155.85,
    avgVolume: 3234567,
    description:
      "PepsiCo, Inc. operates as a food and beverage company worldwide.",
    ceo: "Ramon Laguarta",
    founded: "1965",
    employees: "315,000",
    revenue: "91.5B",
    industry: "Food & Beverages",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "wmt",
    symbol: "WMT",
    name: "Walmart Inc.",
    price: 167.89,
    change: 1.67,
    changePercent: 1.0,
    marketCap: "456B",
    volume: 9876543,
    country: "United States",
    sector: "consumer",
    pe: 26.7,
    dividend: 2.2,
    beta: 0.5,
    eps: 6.28,
    week52High: 173.85,
    week52Low: 143.01,
    avgVolume: 9234567,
    description:
      "Walmart Inc. engages in the operation of retail, wholesale, and other units worldwide.",
    ceo: "Doug McMillon",
    founded: "1962",
    employees: "2,100,000",
    revenue: "648.1B",
    industry: "Retail",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "hd",
    symbol: "HD",
    name: "The Home Depot Inc.",
    price: 378.23,
    change: 4.56,
    changePercent: 1.22,
    marketCap: "387B",
    volume: 2345678,
    country: "United States",
    sector: "consumer",
    pe: 24.8,
    dividend: 2.2,
    beta: 1.0,
    eps: 15.25,
    week52High: 407.94,
    week52Low: 287.03,
    avgVolume: 2876543,
    description:
      "The Home Depot, Inc. operates as a home improvement retailer.",
    ceo: "Ted Decker",
    founded: "1978",
    employees: "475,000",
    revenue: "157.4B",
    industry: "Home Improvement Retail",
    exchange: "NYSE",
    isWatched: false,
  },

  // Energy & Industrial
  {
    id: "xom",
    symbol: "XOM",
    name: "Exxon Mobil Corporation",
    price: 108.45,
    change: 2.34,
    changePercent: 2.21,
    marketCap: "449B",
    volume: 19876543,
    country: "United States",
    sector: "energy",
    pe: 14.6,
    dividend: 3.2,
    beta: 1.1,
    eps: 7.43,
    week52High: 121.58,
    week52Low: 95.77,
    avgVolume: 18234567,
    description:
      "Exxon Mobil Corporation explores for and produces crude oil and natural gas in the United States and internationally.",
    ceo: "Darren Woods",
    founded: "1870",
    employees: "62,000",
    revenue: "344.6B",
    industry: "Oil & Gas",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "cvx",
    symbol: "CVX",
    name: "Chevron Corporation",
    price: 161.23,
    change: 1.89,
    changePercent: 1.19,
    marketCap: "298B",
    volume: 8765432,
    country: "United States",
    sector: "energy",
    pe: 15.2,
    dividend: 3.8,
    beta: 1.0,
    eps: 10.61,
    week52High: 189.68,
    week52Low: 135.37,
    avgVolume: 8234567,
    description:
      "Chevron Corporation engages in integrated energy and chemicals operations worldwide.",
    ceo: "Mike Wirth",
    founded: "1879",
    employees: "47,600",
    revenue: "200.5B",
    industry: "Oil & Gas",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "cat",
    symbol: "CAT",
    name: "Caterpillar Inc.",
    price: 345.67,
    change: 5.23,
    changePercent: 1.54,
    marketCap: "182B",
    volume: 1234567,
    country: "United States",
    sector: "industrial",
    pe: 16.8,
    dividend: 4.4,
    beta: 1.1,
    eps: 20.59,
    week52High: 384.2,
    week52Low: 267.98,
    avgVolume: 1876543,
    description:
      "Caterpillar Inc. manufactures construction and mining equipment, diesel and natural gas engines, industrial gas turbines, and diesel-electric locomotives worldwide.",
    ceo: "Jim Umpleby",
    founded: "1925",
    employees: "114,000",
    revenue: "67.1B",
    industry: "Heavy Machinery",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "ba",
    symbol: "BA",
    name: "The Boeing Company",
    price: 267.89,
    change: -2.34,
    changePercent: -0.87,
    marketCap: "159B",
    volume: 5678901,
    country: "United States",
    sector: "industrial",
    pe: 34.2,
    dividend: 0.0,
    beta: 1.8,
    eps: 7.83,
    week52High: 267.54,
    week52Low: 159.71,
    avgVolume: 6234567,
    description:
      "The Boeing Company designs, develops, manufactures, sales, services, and supports commercial jetliners, military aircraft, satellites, missile defense, human space flight, and launch systems worldwide.",
    ceo: "Dave Calhoun",
    founded: "1916",
    employees: "170,000",
    revenue: "77.8B",
    industry: "Aerospace & Defense",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "ge",
    symbol: "GE",
    name: "General Electric Company",
    price: 167.45,
    change: 3.67,
    changePercent: 2.24,
    marketCap: "184B",
    volume: 4567890,
    country: "United States",
    sector: "industrial",
    pe: 21.8,
    dividend: 1.6,
    beta: 1.3,
    eps: 7.68,
    week52High: 174.28,
    week52Low: 90.98,
    avgVolume: 4234567,
    description:
      "General Electric Company operates as a high-tech industrial company worldwide.",
    ceo: "Larry Culp",
    founded: "1892",
    employees: "172,000",
    revenue: "76.6B",
    industry: "Industrial Conglomerate",
    exchange: "NYSE",
    isWatched: false,
  },

  // Telecommunications & Utilities
  {
    id: "vz",
    symbol: "VZ",
    name: "Verizon Communications Inc.",
    price: 40.23,
    change: 0.34,
    changePercent: 0.85,
    marketCap: "169B",
    volume: 18765432,
    country: "United States",
    sector: "telecommunications",
    pe: 9.1,
    dividend: 6.8,
    beta: 0.4,
    eps: 4.42,
    week52High: 45.36,
    week52Low: 35.32,
    avgVolume: 17234567,
    description:
      "Verizon Communications Inc., through its subsidiaries, provides communications, technology, information, and entertainment products and services to consumers, businesses, and governmental entities worldwide.",
    ceo: "Hans Vestberg",
    founded: "1983",
    employees: "105,400",
    revenue: "134.0B",
    industry: "Telecommunications",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "t",
    symbol: "T",
    name: "AT&T Inc.",
    price: 19.67,
    change: -0.12,
    changePercent: -0.61,
    marketCap: "140B",
    volume: 34567890,
    country: "United States",
    sector: "telecommunications",
    pe: 8.4,
    dividend: 7.4,
    beta: 0.6,
    eps: 2.34,
    week52High: 22.73,
    week52Low: 14.46,
    avgVolume: 31234567,
    description:
      "AT&T Inc. provides telecommunications, media, and technology services worldwide.",
    ceo: "John Stankey",
    founded: "1983",
    employees: "154,470",
    revenue: "122.4B",
    industry: "Telecommunications",
    exchange: "NYSE",
    isWatched: false,
  },

  // International Companies
  {
    id: "asml",
    symbol: "ASML",
    name: "ASML Holding N.V.",
    price: 742.34,
    change: 12.45,
    changePercent: 1.71,
    marketCap: "305B",
    volume: 876543,
    country: "Netherlands",
    sector: "technology",
    pe: 40.2,
    dividend: 1.2,
    beta: 1.6,
    eps: 18.46,
    week52High: 1110.09,
    week52Low: 611.16,
    avgVolume: 934567,
    description:
      "ASML Holding N.V. develops, produces, markets, sells, and services advanced semiconductor equipment systems worldwide.",
    ceo: "Peter Wennink",
    founded: "1984",
    employees: "42,000",
    revenue: "27.6B",
    industry: "Semiconductor Equipment",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "sam",
    symbol: "SAM",
    name: "Samsung Electronics Co., Ltd.",
    price: 72.45,
    change: 1.23,
    changePercent: 1.73,
    marketCap: "432B",
    volume: 5678901,
    country: "South Korea",
    sector: "technology",
    pe: 22.8,
    dividend: 2.4,
    beta: 1.2,
    eps: 3.18,
    week52High: 85.73,
    week52Low: 47.15,
    avgVolume: 5234567,
    description:
      "Samsung Electronics manufactures and sells consumer electronics, information technology and mobile communications, and device solutions worldwide.",
    ceo: "Jong-Hee Han",
    founded: "1969",
    employees: "267,937",
    revenue: "244.2B",
    industry: "Consumer Electronics",
    exchange: "OTC",
    isWatched: false,
  },
  {
    id: "tmc",
    symbol: "TM",
    name: "Toyota Motor Corporation",
    price: 234.56,
    change: 2.34,
    changePercent: 1.01,
    marketCap: "298B",
    volume: 2345678,
    country: "Japan",
    sector: "consumer",
    pe: 9.8,
    dividend: 2.8,
    beta: 0.5,
    eps: 23.94,
    week52High: 248.87,
    week52Low: 182.31,
    avgVolume: 2876543,
    description:
      "Toyota Motor Corporation designs, manufactures, assembles, and sales passenger vehicles, minivans and commercial vehicles, and related parts and accessories worldwide.",
    ceo: "Akio Toyoda",
    founded: "1937",
    employees: "372,817",
    revenue: "274.5B",
    industry: "Automotive",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "nesn",
    symbol: "NESN",
    name: "Nestlé S.A.",
    price: 123.45,
    change: 1.67,
    changePercent: 1.37,
    marketCap: "365B",
    volume: 1234567,
    country: "Switzerland",
    sector: "consumer",
    pe: 20.4,
    dividend: 2.9,
    beta: 0.4,
    eps: 6.05,
    week52High: 132.97,
    week52Low: 103.74,
    avgVolume: 1876543,
    description:
      "Nestlé S.A. operates as a food and beverage company worldwide.",
    ceo: "Ulf Mark Schneider",
    founded: "1866",
    employees: "273,000",
    revenue: "94.4B",
    industry: "Food & Beverages",
    exchange: "OTC",
    isWatched: false,
  },

  // Real Estate & Utilities
  {
    id: "amt",
    symbol: "AMT",
    name: "American Tower Corporation",
    price: 201.23,
    change: 2.45,
    changePercent: 1.23,
    marketCap: "94B",
    volume: 1567890,
    country: "United States",
    sector: "real-estate",
    pe: 52.8,
    dividend: 5.2,
    beta: 0.7,
    eps: 3.81,
    week52High: 215.0,
    week52Low: 169.49,
    avgVolume: 1434567,
    description:
      "American Tower Corporation is a leading independent owner, operator and developer of multitenant communications real estate with a portfolio of approximately 219,000 communications sites.",
    ceo: "Tom Bartlett",
    founded: "1995",
    employees: "5,500",
    revenue: "11.1B",
    industry: "REITs",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "pld",
    symbol: "PLD",
    name: "Prologis Inc.",
    price: 132.45,
    change: 1.89,
    changePercent: 1.45,
    marketCap: "98B",
    volume: 2345678,
    country: "United States",
    sector: "real-estate",
    pe: 24.7,
    dividend: 3.1,
    beta: 1.1,
    eps: 5.36,
    week52High: 149.73,
    week52Low: 102.73,
    avgVolume: 2234567,
    description:
      "Prologis, Inc. is the global leader in logistics real estate with a focus on high-barrier, high-growth markets.",
    ceo: "Hamid Moghadam",
    founded: "1983",
    employees: "2,000",
    revenue: "5.4B",
    industry: "Industrial REITs",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "nee",
    symbol: "NEE",
    name: "NextEra Energy Inc.",
    price: 78.9,
    change: 0.67,
    changePercent: 0.86,
    marketCap: "158B",
    volume: 7890123,
    country: "United States",
    sector: "utilities",
    pe: 22.1,
    dividend: 3.2,
    beta: 0.3,
    eps: 3.57,
    week52High: 85.57,
    week52Low: 64.37,
    avgVolume: 7234567,
    description:
      "NextEra Energy, Inc., through its subsidiaries, generates, transmits, distributes, and sells electric power to retail and wholesale customers in North America.",
    ceo: "John Ketchum",
    founded: "1925",
    employees: "15,000",
    revenue: "28.1B",
    industry: "Electric Utilities",
    exchange: "NYSE",
    isWatched: false,
  },

  // Additional Top Companies
  {
    id: "shop",
    symbol: "SHOP",
    name: "Shopify Inc.",
    price: 67.89,
    change: 2.34,
    changePercent: 3.57,
    marketCap: "85B",
    volume: 9876543,
    country: "Canada",
    sector: "technology",
    pe: 68.9,
    dividend: 0.0,
    beta: 1.8,
    eps: 0.98,
    week52High: 91.57,
    week52Low: 48.56,
    avgVolume: 8765432,
    description:
      "Shopify Inc., a commerce company, provides a commerce platform and services in Canada, the United States, Europe, the Middle East, Africa, the Asia Pacific, and Latin America.",
    ceo: "Tobias Lütke",
    founded: "2006",
    employees: "12,000",
    revenue: "7.1B",
    industry: "E-commerce Software",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "amd",
    symbol: "AMD",
    name: "Advanced Micro Devices Inc.",
    price: 187.43,
    change: 8.67,
    changePercent: 4.85,
    marketCap: "303B",
    volume: 34567890,
    country: "United States",
    sector: "technology",
    pe: 42.3,
    dividend: 0.0,
    beta: 1.9,
    eps: 4.43,
    week52High: 227.3,
    week52Low: 93.12,
    avgVolume: 31234567,
    description:
      "Advanced Micro Devices, Inc. operates as a semiconductor company worldwide.",
    ceo: "Lisa Su",
    founded: "1969",
    employees: "31,000",
    revenue: "22.7B",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "intc",
    symbol: "INTC",
    name: "Intel Corporation",
    price: 51.23,
    change: -0.89,
    changePercent: -1.71,
    marketCap: "206B",
    volume: 25678901,
    country: "United States",
    sector: "technology",
    pe: 18.7,
    dividend: 2.4,
    beta: 0.8,
    eps: 2.74,
    week52High: 68.49,
    week52Low: 18.51,
    avgVolume: 23456789,
    description:
      "Intel Corporation designs, manufactures, and sells computer products and technologies worldwide.",
    ceo: "Pat Gelsinger",
    founded: "1968",
    employees: "131,900",
    revenue: "63.1B",
    industry: "Semiconductors",
    exchange: "NASDAQ",
    isWatched: false,
  },
  {
    id: "brkb",
    symbol: "BRK.B",
    name: "Berkshire Hathaway Inc.",
    price: 445.67,
    change: 3.45,
    changePercent: 0.78,
    marketCap: "970B",
    volume: 2345678,
    country: "United States",
    sector: "finance",
    pe: 9.2,
    dividend: 0.0,
    beta: 0.9,
    eps: 48.43,
    week52High: 467.8,
    week52Low: 344.73,
    avgVolume: 2876543,
    description:
      "Berkshire Hathaway Inc., through its subsidiaries, provides insurance and reinsurance, utilities and energy, freight rail transportation, and various other products and services worldwide.",
    ceo: "Warren Buffett",
    founded: "1839",
    employees: "396,500",
    revenue: "364.5B",
    industry: "Financial Conglomerate",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "dis",
    symbol: "DIS",
    name: "The Walt Disney Company",
    price: 112.45,
    change: 1.89,
    changePercent: 1.71,
    marketCap: "205B",
    volume: 8765432,
    country: "United States",
    sector: "telecommunications",
    pe: 67.8,
    dividend: 0.88,
    beta: 1.2,
    eps: 1.66,
    week52High: 123.74,
    week52Low: 78.73,
    avgVolume: 8234567,
    description:
      "The Walt Disney Company entertains, informs, and inspires people around the globe through the power of unparalleled storytelling.",
    ceo: "Bob Iger",
    founded: "1923",
    employees: "220,000",
    revenue: "82.7B",
    industry: "Entertainment",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "v",
    symbol: "V",
    name: "Visa Inc.",
    price: 278.34,
    change: 2.67,
    changePercent: 0.97,
    marketCap: "586B",
    volume: 5678901,
    country: "United States",
    sector: "finance",
    pe: 32.8,
    dividend: 0.52,
    beta: 1.0,
    eps: 8.48,
    week52High: 290.96,
    week52Low: 244.11,
    avgVolume: 5234567,
    description:
      "Visa Inc. operates as a payments technology company worldwide.",
    ceo: "Ryan McInerney",
    founded: "1958",
    employees: "26,500",
    revenue: "32.7B",
    industry: "Payment Processing",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "ma",
    symbol: "MA",
    name: "Mastercard Incorporated",
    price: 478.9,
    change: 5.67,
    changePercent: 1.2,
    marketCap: "449B",
    volume: 2345678,
    country: "United States",
    sector: "finance",
    pe: 33.2,
    dividend: 0.57,
    beta: 1.1,
    eps: 14.43,
    week52High: 490.0,
    week52Low: 359.81,
    avgVolume: 2876543,
    description:
      "Mastercard Incorporated, a technology company, provides transaction processing and other payment-related products and services worldwide.",
    ceo: "Michael Miebach",
    founded: "1966",
    employees: "33,400",
    revenue: "25.1B",
    industry: "Payment Processing",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "unh",
    symbol: "UNH",
    name: "UnitedHealth Group Incorporated",
    price: 567.89,
    change: 7.23,
    changePercent: 1.29,
    marketCap: "531B",
    volume: 3456789,
    country: "United States",
    sector: "healthcare",
    pe: 24.1,
    dividend: 1.9,
    beta: 0.7,
    eps: 23.56,
    week52High: 629.01,
    week52Low: 445.68,
    avgVolume: 3234567,
    description:
      "UnitedHealth Group Incorporated operates as a diversified health care company in the United States.",
    ceo: "Andrew Witty",
    founded: "1977",
    employees: "440,000",
    revenue: "371.6B",
    industry: "Health Insurance",
    exchange: "NYSE",
    isWatched: false,
  },
  {
    id: "adbe",
    symbol: "ADBE",
    name: "Adobe Inc.",
    price: 512.34,
    change: 8.9,
    changePercent: 1.77,
    marketCap: "231B",
    volume: 1234567,
    country: "United States",
    sector: "technology",
    pe: 44.8,
    dividend: 0.0,
    beta: 1.1,
    eps: 11.44,
    week52High: 638.25,
    week52Low: 433.97,
    avgVolume: 1876543,
    description:
      "Adobe Inc. operates as a diversified software company worldwide.",
    ceo: "Shantanu Narayen",
    founded: "1982",
    employees: "29,239",
    revenue: "19.4B",
    industry: "Software",
    exchange: "NASDAQ",
    isWatched: false,
  },
];

// Generate chart data for companies
export const generateCompanyChartData = (symbol: string) => {
  const basePrice =
    TOP_50_COMPANIES.find((c) => c.symbol === symbol)?.price || 100;
  const data = [];

  for (let i = 30; i >= 0; i--) {
    const date = new Date();
    date.setDate(date.getDate() - i);

    // Generate realistic price movement
    const volatility = 0.02 + Math.random() * 0.03; // 2-5% volatility
    const change = (Math.random() - 0.5) * volatility;
    const previousPrice =
      i === 30 ? basePrice : data[data.length - 1]?.close || basePrice;

    const open = previousPrice * (1 + (Math.random() - 0.5) * 0.01);
    const close = open * (1 + change);
    const high = Math.max(open, close) * (1 + Math.random() * 0.02);
    const low = Math.min(open, close) * (1 - Math.random() * 0.02);
    const volume = Math.floor(Math.random() * 50000000 + 10000000);

    data.push({
      date: date.toISOString().split("T")[0],
      time: date.getTime(),
      open: parseFloat(open.toFixed(2)),
      high: parseFloat(high.toFixed(2)),
      low: parseFloat(low.toFixed(2)),
      close: parseFloat(close.toFixed(2)),
      volume,
    });
  }

  return data;
};
